@extends('errors.layout')
@section('code', '404')
@section('title', 'Page Not Found')
@section('heading', 'This Page Has Gone Off the Grid')
@section('message', 'The page you are looking for may have moved, been removed, or never existed. Let us guide you back to a working digital experience.')
