<aside class="blog-sidebar article-sidebar">
    <div class="blog-sidebar-card"><h3>Search</h3><form class="blog-search" action="{{ route('blog.index') }}" method="GET"><input type="search" name="search" placeholder="Search articles..." aria-label="Search articles" value="{{ request('search') }}"><button type="submit" aria-label="Search"><i class="fa-solid fa-magnifying-glass"></i></button></form></div>
    @if($categories->isNotEmpty())
        <div class="blog-sidebar-card"><h3>Categories</h3><a class="blog-category-link" href="{{ route('blog.index') }}"><span><i class="fa-solid fa-table-cells-large"></i> All Categories</span><strong>({{ $articles->count() }})</strong></a>@foreach($categories as $category)<a class="blog-category-link" href="{{ route('blog.index', ['category' => $category['name']]) }}"><span><i class="{{ $category['icon'] }}"></i> {{ $category['name'] }}</span><strong>({{ $category['count'] }})</strong></a>@endforeach</div>
    @endif
    <div class="blog-sidebar-card"><h3>Popular Posts</h3>@foreach($articles->where('slug', '!=', $article->slug)->take(4) as $popular)<a class="popular-post" href="{{ route('blog.show', $popular->slug) }}"><img src="{{ url($popular->image) }}" alt="{{ $popular->title }}" loading="lazy" decoding="async"><span><strong>{{ \Illuminate\Support\Str::limit($popular->title, 45) }}</strong><small>{{ $popular->date }}</small></span></a>@endforeach</div>
    <div class="blog-sidebar-card blog-newsletter"><span class="blog-newsletter-icon"><i class="fa-solid fa-paper-plane"></i></span><h3>Subscribe to Our Newsletter</h3><p>Get the latest insights and updates delivered straight to your inbox.</p><form onsubmit="return false;"><input type="email" placeholder="Enter your email address" aria-label="Email address"><button type="submit">Subscribe Now <i class="fa-solid fa-arrow-right"></i></button></form></div>
    <div class="article-cta"><i class="fa-solid fa-arrow-trend-up"></i><h3>Ready to Grow<br>Your Business?</h3><p>Let’s build a digital strategy that drives traffic, generates leads, and grows your revenue.</p><a href="{{ route('index') }}#contact">Get A Free Consultation <i class="fa-solid fa-arrow-right"></i></a></div>
</aside>
